### ISSUE TITLE
[Feature Request] Compare selected files in file list

### ISSUE THREAD

**Issue by lonix1** [danielroedl/vsc-meld-diff#11]
In sidebar (file explorer), we must select one file and choose choose the "select" option, then select another file and choose the "compare" option.

It would be nice to select two files, and then just choose a "compare" option. A single-step process instead of two.

**Comment by danielroedl** [comment]
New version 1.3.0 with your feature is released! 😄
See the new option in file explorer [Compare all selected files/folders using meld](https://github.com/danielroedl/vsc-meld-diff#compare-all-selected-filesfolders-using-meld)

**Comment by lonix1** [comment]
Awesome thanks!
