### ISSUE TITLE
Meld Diff Error: Error running diff command! StdErr

### ISSUE THREAD

**Issue by AoiKagase** [danielroedl/vsc-meld-diff#17]
It does not seem to work properly in Japanese environment.

![image](https://user-images.githubusercontent.com/26139931/170660842-ee4dcd11-9718-42c3-9a6d-fca7e24e1aa0.png)

![image](https://user-images.githubusercontent.com/26139931/170660574-250d3f34-6346-440b-ad7b-eaa0ee433f3d.png)

**Comment by danielroedl** [comment]
First you have to use single backslashes in your path. And because you have spaces in your path you have to put into quotation marks.

Please try
"C:\Program Files (x86)\Meld\meld.exe"

**Comment by danielroedl** [comment]
I published a bug fix for this. With the current version 1.3.3 it should also work if you have no quotes in the setting of the meld command. Please try this and let me know if it is working for you.

**Comment by AoiKagase** [comment]
Thanks, I confirmed that it works fine.
