### ISSUE TITLE
Tray Error Notification When Using Beyond Compare

### ISSUE THREAD

**Issue by opus131** [danielroedl/vsc-meld-diff#22]
First of all thank you for this extension!

I have configured BeyondCompare as my diff tool, and it opens just fine - but when I close the BeyondCompare app, or even when closing just one of the compared files inside BC, a VS Code tray notification pops up: "Meld Diff Error: Error running diff command! StdErr:"

Is there any way to suppress that?

**Comment by danielroedl** [comment]
I don't know the reason, but BC ends with an error code when it is closed.

I just released a version `1.4.0` with a new option to suppress this error message.

**Comment by opus131** [comment]
I can confirm this resolved the issue. Thank you for your fantastic work! 🚀

**Comment by opus131** [comment]
Issue resolved in `1.4.0`
