### ISSUE TITLE
New feature: Open Meld from Diff Editor

### ISSUE THREAD

**Issue by ryancu7** [danielroedl/vsc-meld-diff#26]
Visual Studio Code has its own diff editor viewer but it is not as good as Meld (e.g. empty space is added instead of fluid synchronised scrolling). I use the GitLab Workflows extension to review merge requests and it uses the built in Visual Studio Code editor (the files for the diff being viewed are not on disk). 

Could you please add a button to the built-in VSCode diff view to open the current diff in Meld? 

The Beyond Compare VSCode extension has this feature:
* https://github.com/ScooterSoftware/bcompare-vscode?tab=readme-ov-file#open-beyond-compare-from-diff-editor
* https://github.com/ScooterSoftware/bcompare-vscode/blob/6abe51fe7ae46c1abbcbc830dbb169dab3dad274/package.json#L124
* https://github.com/ScooterSoftware/bcompare-vscode/blob/6abe51fe7ae46c1abbcbc830dbb169dab3dad274/src/extension.ts#L1241
  * Left/right files are saved to a temporary location so external editor can load them.

**Comment by danielroedl** [comment]
Thanks for the idea @ryancu7 I like it.
Also thanks to @pbaldauf  for implementing it!
The feature will be available in the next release.
