### ISSUE TITLE
support to use meld for resolving git conflicts in vs-code

### ISSUE THREAD

**Issue by hbinkle** [danielroedl/vsc-meld-diff#3]
meld has a great comparison and three way merge.
Please make it possible to use it for resolving git merge conflicts.

**Comment by danielroedl** [comment]
I also would love to add this feature but till now there is no possible way (as I know) to replace the internal diff implementation via a extension.
I will let this issue open. Maybe this is possible in future releases of code.

**Comment by asherlporetz** [comment]
Was able to replace `meld` with `charm diff` for diff view. Maybe use intellij or variants (like charm or webstorm) for 3-way merge as well. As an enhancement, note that intellij/charm diff can accept directories so if you wanted diff HEAD^ HEAD maybe you can checkout HEAD^ in a temporary dir then pass that and the current dir to `idea diff` to compare not just a single file but all the files in a commit. Haven't explored but `sourcetree` might also work.
```
idea diff <left> <right>
idea merge <local> <remote> [base] <merged>
```

**Comment by lonix1** [comment]
[This extension](https://marketplace.visualstudio.com/items?itemName=david-rickard.git-diff-and-merge-tool) has a way to do that, if I'm understanding correctly? Would be nice for this extension to be able to do that too.

**Comment by danielroedl** [comment]
New function to use meld diff in source control added with version 1.2.0
